services:
  php:
    container_name: bbphp-emailsender-smtp-adapter-php
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
      - composer-cache:/tmp/composer-cache
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache
      GITHUB_TOKEN: ${GITHUB_TOKEN:?GITHUB_TOKEN no definido en .env}
      COMPOSER_AUTH: "{\"github-oauth\":{\"github.com\":\"${GITHUB_TOKEN:?GITHUB_TOKEN no definido en .env}\"}}"
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]

volumes:
  composer-cache: